# Generated by Django 3.2 on 2022-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_auto_20220426_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
